{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tillerless-helm-release-exporter.fullname" . }}
  labels:
{{ include "tillerless-helm-release-exporter.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "tillerless-helm-release-exporter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "tillerless-helm-release-exporter.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}


