{{- if .Values.podSecurityPolicy.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp-{{ include "tillerless-helm-release-exporter.fullname" . }}
  labels:
{{ include "tillerless-helm-release-exporter.labels" . | indent 4 }}
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "tillerless-helm-release-exporter.fullname" . }}
{{- end -}}
