{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tillerless-helm-release-exporter.fullname" . }}
  labels:
{{ include "tillerless-helm-release-exporter.labels" . | indent 4 }}
imagePullSecrets:
{{ toYaml .Values.serviceAccount.imagePullSecrets | indent 2 }}
{{- end -}}

