apiVersion: v1
kind: Service
metadata:
  name: {{ include "tillerless-helm-release-exporter.fullname" . }}
  labels:
    {{- include "tillerless-helm-release-exporter.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.service.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    {{- if .Values.metrics.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.port | quote }}
    {{- end }}
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "tillerless-helm-release-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
